name: Build Zygisk Menu

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Install Missing CMake 3.18.1
        run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.18.1"

      - name: Build Module
        run: ./gradlew assembleRelease

      - name: Upload Module zip
        uses: actions/upload-artifact@v4
        with:
          name: Zygisk-Mod-Menu
          path: |
            out/*.zip
            module/build/outputs/**/*.zip
            app/build/outputs/**/*.apk
